package org.vtb.multibanking.model.quest;

public enum QuestType {
    ACCOUNT_OPENING, TRANSFER_AMOUNT, OPERATION_COUNT,
    AUTOPAYMENT_SETUP, FRIEND_INVITATION, PRODUCT_PURCHASE,
    DEPOSIT_AMOUNT, PAYMENT_OPERATION,

    REFERRAL
}
